//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.21 at 12:38:52 PM EEST 
//


package visa.pratica.types.xml.app;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PraticaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PraticaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IdPratica" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Richiedente" type="{http://xml.types.pratica.visa/app}RichiedenteType"/>
 *         &lt;element name="TitoloViaggio" type="{http://xml.types.pratica.visa/app}TitoloViaggioType"/>
 *         &lt;element name="Visto" type="{http://xml.types.pratica.visa/app}VistoType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PraticaType", propOrder = {
    "idPratica",
    "richiedente",
    "titoloViaggio",
    "visto"
})
public class PraticaType {

    @XmlElement(name = "IdPratica", required = true)
    protected String idPratica;
    @XmlElement(name = "Richiedente", required = true)
    protected RichiedenteType richiedente;
    @XmlElement(name = "TitoloViaggio", required = true)
    protected TitoloViaggioType titoloViaggio;
    @XmlElement(name = "Visto", required = true)
    protected VistoType visto;

    /**
     * Gets the value of the idPratica property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdPratica() {
        return idPratica;
    }

    /**
     * Sets the value of the idPratica property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdPratica(String value) {
        this.idPratica = value;
    }

    /**
     * Gets the value of the richiedente property.
     * 
     * @return
     *     possible object is
     *     {@link RichiedenteType }
     *     
     */
    public RichiedenteType getRichiedente() {
        return richiedente;
    }

    /**
     * Sets the value of the richiedente property.
     * 
     * @param value
     *     allowed object is
     *     {@link RichiedenteType }
     *     
     */
    public void setRichiedente(RichiedenteType value) {
        this.richiedente = value;
    }

    /**
     * Gets the value of the titoloViaggio property.
     * 
     * @return
     *     possible object is
     *     {@link TitoloViaggioType }
     *     
     */
    public TitoloViaggioType getTitoloViaggio() {
        return titoloViaggio;
    }

    /**
     * Sets the value of the titoloViaggio property.
     * 
     * @param value
     *     allowed object is
     *     {@link TitoloViaggioType }
     *     
     */
    public void setTitoloViaggio(TitoloViaggioType value) {
        this.titoloViaggio = value;
    }

    /**
     * Gets the value of the visto property.
     * 
     * @return
     *     possible object is
     *     {@link VistoType }
     *     
     */
    public VistoType getVisto() {
        return visto;
    }

    /**
     * Sets the value of the visto property.
     * 
     * @param value
     *     allowed object is
     *     {@link VistoType }
     *     
     */
    public void setVisto(VistoType value) {
        this.visto = value;
    }

}
