//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.21 at 12:38:52 PM EEST 
//


package visa.pratica.types.xml.app;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the visa.pratica.types.xml.app package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: visa.pratica.types.xml.app
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InvioPraticaRequest }
     * 
     */
    public InvioPraticaRequest createInvioPraticaRequest() {
        return new InvioPraticaRequest();
    }

    /**
     * Create an instance of {@link PraticaType }
     * 
     */
    public PraticaType createPraticaType() {
        return new PraticaType();
    }

    /**
     * Create an instance of {@link InvioPraticaResponse }
     * 
     */
    public InvioPraticaResponse createInvioPraticaResponse() {
        return new InvioPraticaResponse();
    }

    /**
     * Create an instance of {@link DeliveryType }
     * 
     */
    public DeliveryType createDeliveryType() {
        return new DeliveryType();
    }

    /**
     * Create an instance of {@link RichiedenteType }
     * 
     */
    public RichiedenteType createRichiedenteType() {
        return new RichiedenteType();
    }

    /**
     * Create an instance of {@link TitoloViaggioType }
     * 
     */
    public TitoloViaggioType createTitoloViaggioType() {
        return new TitoloViaggioType();
    }

    /**
     * Create an instance of {@link VistoType }
     * 
     */
    public VistoType createVistoType() {
        return new VistoType();
    }

}
