//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.21 at 12:38:52 PM EEST 
//


package visa.pratica.types.xml.app;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for VistoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VistoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tipoVisto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="motivazioneVisto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="durataSoggiorno" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="dataInizioSoggiorno" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="dataFineSoggiorno" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VistoType", propOrder = {
    "tipoVisto",
    "motivazioneVisto",
    "durataSoggiorno",
    "dataInizioSoggiorno",
    "dataFineSoggiorno"
})
public class VistoType {

    @XmlElement(required = true)
    protected String tipoVisto;
    @XmlElement(required = true)
    protected String motivazioneVisto;
    protected int durataSoggiorno;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataInizioSoggiorno;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataFineSoggiorno;

    /**
     * Gets the value of the tipoVisto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoVisto() {
        return tipoVisto;
    }

    /**
     * Sets the value of the tipoVisto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoVisto(String value) {
        this.tipoVisto = value;
    }

    /**
     * Gets the value of the motivazioneVisto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMotivazioneVisto() {
        return motivazioneVisto;
    }

    /**
     * Sets the value of the motivazioneVisto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMotivazioneVisto(String value) {
        this.motivazioneVisto = value;
    }

    /**
     * Gets the value of the durataSoggiorno property.
     * 
     */
    public int getDurataSoggiorno() {
        return durataSoggiorno;
    }

    /**
     * Sets the value of the durataSoggiorno property.
     * 
     */
    public void setDurataSoggiorno(int value) {
        this.durataSoggiorno = value;
    }

    /**
     * Gets the value of the dataInizioSoggiorno property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataInizioSoggiorno() {
        return dataInizioSoggiorno;
    }

    /**
     * Sets the value of the dataInizioSoggiorno property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataInizioSoggiorno(XMLGregorianCalendar value) {
        this.dataInizioSoggiorno = value;
    }

    /**
     * Gets the value of the dataFineSoggiorno property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataFineSoggiorno() {
        return dataFineSoggiorno;
    }

    /**
     * Sets the value of the dataFineSoggiorno property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataFineSoggiorno(XMLGregorianCalendar value) {
        this.dataFineSoggiorno = value;
    }

}
