//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 04:25:54 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ee.spring.corso/ws/UserService", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package corso.spring.ee.ws.userservice;
