//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.03 at 12:42:38 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://corso.spring.ee/ws/UserService", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package corso.spring.ee.demo.ws.basic.xmltypes;
